### ISSUE TITLE
Privacy section expansion

### ISSUE THREAD

**Issue by Zyst** [DarylPinto/stickers-for-discord#4]
Hey! I found that the privacy section @ https://stickersfordiscord.com/terms.html is a bit barebones.

>This service does not collect any personal or private information. All information collected from Discord servers (Role IDs, User IDs) or from Google Analytics is gathered for the explicit purpose of providing functionality to the service or aggregating data to help us improve the service.

In particular in this section I do not understand what data is being collected both on the website, and by the bot.

Would it be possible to expand upon what data is being collected?

**Comment by Zyst** [comment]
Here's what I've found digging so far in the general bot code:

* Your server name (guild), and id is saved. 
* The names, avatars, and IDs of every user in the server is saved.
* Every time a user uses a bot command their request is saved in a database tied to their user ID

Did I miss something?

**Comment by DarylPinto** [comment]
Hi there, I'll clarify what's being collected:

- Your server name, server image, and server id is saved when the bot is added to the server. This is so that a page can be created for your server that will be viewable whenever someone uses the `$stickers` command in Discord or logs into the site and clicks on "Servers".

- Stickers for Discord *does not* collect info about every user on your server. IDs of users with special permissions* in your server are saved so that the bot knows who is able to perform what actions (Add stickers, Delete stickers, Blacklist a role etc.)

- The name and avatar of a user is *only saved* if a user private message the bot or logs into the website. This is so that a page can be created for a user, which is viewable whenever they private message the bot `$stickers` in Discord or log into the site and click "Personal Stickers".

- Bot command requests are handled by the bot in real time and are not saved to a database or tied to an ID.

Do you have any suggestions on how I can make the privacy section clearer?

**Comment by Zyst** [comment]
Just straight up outlining what data is being collected might be helpful. I was originally outlining it below, but let me open a PR, and we can move the discussion there. See #5

**Comment by Zyst** [comment]
Please let me know how you feel about the phrasing. This could be changed by you, or you could request for me to change it, and I'd be more than happy to do so!
